@baseUrl = http://localhost:3333
@authToken = {{authenticate_with_password.response.body.token}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Gabriel Freitas",
  "email": "gabriel@example.com",
  "password": "123456"
}

###

# @name authenticate_with_password
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "gabriel@example.com",
  "password": "123456"
}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name request_password_recover
POST {{baseUrl}}/password/recover
Content-Type: application/json

{
  "email": "gabriel@example.com"
}

###

# @name reset_password
POST {{baseUrl}}/password/reset
Content-Type: application/json

{
  "code": "c3c218a9-de69-4f9e-a485-a2f00bc8b2cf",
  "password": "123456"
}

###

# @name create_organization
POST {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Organization 01",
  "domain": "organization01.com",
  "shouldAttachUsersByDomain": true
}

###

# @name get_membership
GET {{baseUrl}}/organizations/organization-01/membership
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_organization
GET {{baseUrl}}/organizations/organization-01
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_organizations
GET {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_organization
PUT {{baseUrl}}/organizations/organization-01
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Organization 01",
  "domain": "organization01.com",
  "shouldAttachUsersByDomain": true
}

###

# @name shutdown_organization
DELETE {{baseUrl}}/organizations/organization-to-be-deleted
Authorization: Bearer {{authToken}}

###

# @name transfer_organization
PATCH {{baseUrl}}/organizations/organization-01
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "transferToUserId": "user-id"
}

###

# @name create_project
POST {{baseUrl}}/organizations/organization-01/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Project 01",
  "description": "Project 01 Description"  
}

###

# @name delete_project
DELETE {{baseUrl}}/organizations/organization-01/projects/project-to-be-deleted-id
Authorization: Bearer {{authToken}}

###

# @name get_project
GET {{baseUrl}}/organizations/organization-01/projects/project-01
Authorization: Bearer {{authToken}}

###

# @name get_projects
GET {{baseUrl}}/organizations/organization-01/projects
Authorization: Bearer {{authToken}}

###

# @name update_project
PUT {{baseUrl}}/organizations/organization-01/projects/project-01
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Project 01 Updated",
  "description": "Project 01 Description"
}

###

# @name get_members
GET {{baseUrl}}/organizations/organization-01/members
Authorization: Bearer {{authToken}}

###

# @name update_member
PUT {{baseUrl}}/organizations/organization-01/members/user-id
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "ADMIN"
}

###

# @name remove_member
DELETE {{baseUrl}}/organizations/organization-01/members/user-id-to-be-removed
Authorization: Bearer {{authToken}}

###

# @name create_invite
POST {{baseUrl}}/organizations/organization-01/invites
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "new-member-01@example.com",
  "role": "ADMIN"
}

###

# @name get_invite
GET {{baseUrl}}/invites/b57ab849-2bbb-4a26-8337-d6e86fee304b

###

# @name get_invites
GET {{baseUrl}}/organizations/organization-01/invites
Authorization: Bearer {{authToken}}
